config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_page#home'
  get  '/help'    , to: 'static_page#help'    
  get  '/about'   , to: 'static_page#about'   
  get  '/mission' , to: 'static_page#mission' 
  get  '/contact' , to: 'static_page#contact'
  get  '/logo'    , to: 'static_page#logo'

  resources :users
  get  '/signup'  , to: 'users#new'
  post '/signup'  , to: 'users#create'

  get  '/login'   , to: 'sessions#new'
  post '/login'   , to: 'sessions#create'
  delete  '/logout'  , to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  validates( :name,
            presence: true,
            uniqueness: true,
            length: { maximum:50, minimum:4} )
  validates( :email,
            presence: true,
            uniqueness: { case_sensitive:false },
            length: { maximum:255 },
            format: { with: /\A[\w\d\-.]+@([a-z\d\-]+\.)+[a-z]+\z/i } )
  has_secure_password
  validates( :password,
            presence: true,
            length: { minimum:6 } )

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def mission
  end

  def contact
  end

  def logo
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:success] = "Success: created user #{@user.name}."
      render 'show'
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def activeProvide(path)
    if current_page?(path)
      "active"
    else
      ""
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the user
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user 
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id:user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashmesj.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <%# content_tag(:div, message, class: "alert alert-#{message_type}:) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="d-flex flex-row-reverse">
    <div class="p-1"><%= link_to "About",   about_path  , class:"footlink"%></div>
    <div class="p-1"><%= link_to "Contact", contact_path, class:"footlink"%></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-dark navbar-expand bg-dark flex-column flex-md-row sticky-top">
  <%= link_to image_tag("noo.png", alt:"Noo logo", size:"30x30", class:"rounded logo"),logo_url, class:"navbar-brand logo-button rounded" %>
    <div class="navbar-nav-scroll">
    <ul class="navbar-nav flex-row">
      <li class="nav-item rounded <%= activeProvide(root_path)   %>"><%= link_to "Home",    root_path,    class:"nav-link"%></li>
      <li class="nav-item rounded <%= activeProvide(help_path)   %>"><%= link_to "Help",    help_path,    class:"nav-link"%></li>
      <li class="nav-item rounded <%= activeProvide(about_path)  %>"><%= link_to "About",   about_path,   class:"nav-link"%></li>
      <li class="nav-item rounded <%= activeProvide(mission_path)%>"><%= link_to "Mission", mission_path, class:"nav-link"%></li>
    </ul>
    </div>
    <ul class="navbar-nav flex-row ml-md-auto">
    <% if logged_in? %>
    <li class="dropdown nav-item rounded">
      <a href="#" class="dropdown-toggle dropdown-link" data-toggle="dropdown">account<b class="caret"></b>
      </a>
      <ul class="dropdown-menu bg-dark">
        <li class="nav-item"><%= link_to "profile", current_user , class:"dropdown-link"%></li>
        <li class="nav-item"><%= link_to "settings", "#", class:"dropdown-link"%></li>
        <li class="divider"></li>
        <li class="nav-item"><%= link_to "log out", logout_path, method: :delete, class:"dropdown-link"%></li>
      </li>
     <% else %>
       <li class="nav-item rounded <%= activeProvide(login_path)%>"><%= link_to "Log in", login_path, class:"nav-link" %></li>
   <% end %>
   </ul>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> ~ NooApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashmesj' %>
    <%= yield %>
    <%= debug(params) %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger mb-0">
    <div><strong>The form contains <%= pluralize(object.errors.count, "error") %>.</strong></div>
    <hr class="mt-1 mb-2">
    <ul class="mb-1">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/about.html.erb
<%= provide(:title, "About") %>
<div class="headertitle">About</div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="big_plate col-md-10 center mt-md-4">
    <%= image_tag("self.jpeg", alt:"creator's avatar", size:"200x200", class:"logo logo-special mb-md-3 mt-3") %>
    <p>This website is created by LaseryLee<br>
    email: laserylee2013@gmail.com<br>
    source: <a href="https://github.com/laserylee/noo_app">https://github.com/laserylee/noo_app<a></p>
  </div>
</div>

app/views/static_page/contact.html.erb
<%= provide(:title, "Contact") %>

<h1>Contact</h1>
<br>
<p>
  Telephone no.: <br>
  Email address: <br>
  Address :
</p>

app/views/static_page/help.html.erb
<%= provide(:title, "Help") %>

<div class="row ml-md-5 ml-sm-3">
  <div class="col-sm-5 col-md-3 border big_plate">
    <div ><h5 class="mt-3">Search</h5><p>Here is some utility of searching ...</p></div>
    <div><h5>Create</h5><p>Here is some utility of create ...</p></div>
    <div><h5>Legend</h5><p>This outfit is ideal for any tibian who loves clowning around or joking other people. </p></div>
    <div><h5>Location</h5><p>In and around Thais, Edron, Cormaya, Kazordoon, Carlin, Venore, Port Hope, Liberty Bay, and several other locations </p></div>
    <div><h5>Dangers</h5><p>Lesser creatures, Slimes, Rotworms, Ghouls, Stalkers, Demon Skeletons, Dwarf Guard, Quaras, all kind of Minotaurs, all kind of Apes, all kind of Orcs, Dragon, and others. </p></div>
    <div><h5>Rewards</h5><p>A Jester Staff, a Jester Hat and Jester Outfits and addons, achievements: Allow Cookies?, Perfect Fool and Fool at Heart.</p></div>
  </div>
  <div class="col-sm-6 col-md-8 border big_plate">
    <div><h4 class="mt-3">Becoming the Carry!</h4><p>In a hedge fund environment, carried interest is usually referred to as a "performance fee" and because it invests in liquid investments, it is often able to pay carried interest annually if the fund has generated a profit. They have historically centered on 20%, but have had greater variability than those of private equity funds. In extreme cases performance fees reach as high as 44% of a fund's profits but is usually between 15% and 20%.</p></div>
    <div><h4>Cut the Trees!</h4><p>When Erig.net became a Supported Fansite on November 24, 2005, TibiaWiki, being part of that site, became a supported fansite too. However TibiaWiki had an immense slowness during peak times under the old domain because of its popularity among Tibia players. The new domain hosted by Wikia provides a better availability of this well-liked fansite, which has been supported since January 22, 2008. With the introduction of the new fansite programme, TibiaWiki became a promoted fansite, on November 11, 2008.</p></div>
  </div>
</div>

app/views/static_page/home.html.erb
<%= provide(:title, "Home") %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 border">
      One of three columns One of three columns One of three columns One of three columns One of three columns
    </div>
    <div class="col-md-4 border">
      One of three columns One of three columns One of three columns One of three columns One of three columns 
    </div>
    <div class="col-md-4">
      One of three columns One of three columns One of three columns One of three columns One of three columns 
    </div>
  </div>
</div>

app/views/static_page/logo.html.erb
<% provide(:title, NooApp) %>
<div class="jumbotron center">
  <%= image_tag("noo.png", alt:"Noo logo", class:"rounded logo logo-special") %>
</div>

app/views/static_page/mission.html.erb
<%= provide(:title, "Mission") %>

<h1>Mission</h1>
<p>Find me in app/views/static_page/mission.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="headertitle">Sign Up</div>
<div class="row">
  <div class="col-md-6 offset-md-3 col-sm-8 offset-sm-2 mt-3">
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class:'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>

    <%= f.label :password_confirmation , "Confirmation" %>
    <%= f.password_field :password_confirmation, class:'form-control' %>

    <%= f.submit "Create my account!", class:"btn btn-primary" %>

  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:header, @user.name) %>